name: Build Docker Image

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      dockerfile_name:
        description: 'chose build dockerfile name'
        required: true
        type: choice
        default: 'Dockerfile.lighttpd'
        options:
          - 'Dockerfile.caddy'
          - 'Dockerfile.darkhttpd'
          - 'Dockerfile.lighttpd'
          - 'Dockerfile.nginx'

permissions:
  contents: read
  packages: write

env:
  REPO_URL: https://github.com/MetaCubeX/metacubexd
  REPO_BRANCH: gh-pages
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/metacubexd
  DOCKERHUB_IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/metacubexd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone gh-pages branch
        id: source
        run: |
          git clone --depth=1 $REPO_URL -b $REPO_BRANCH metacubexd
          cd metacubexd
          SUBJECT=$(git log -1 --pretty=%s)
          if [[ "$SUBJECT" =~ ^v[0-9]+(\.[0-9]+)* ]]; then
            VERSION="${BASH_REMATCH[0]}"
          else
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ github.event.inputs.dockerfile_name || github.event.client_payload.dockerfile_name }}
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.source.outputs.version }}
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_IMAGE }}:${{ steps.source.outputs.version }}
            ${{ env.DOCKERHUB_IMAGE }}:latest
